### ISSUE TITLE
Create application layout. Questions and Requests

### ISSUE THREAD

**Issue by JerzyKukla** [EndorFit/EndorFit#1]
If you have any question or request/proposal related to app layout, please give me know in this issue.
For request/proposal describe what you think layout should look like or just draw your idea in paint and past it here.

For now layout looks like below:
- Sing up/Sign in activity
![layout_signIn](https://user-images.githubusercontent.com/48810274/77111197-31344780-6a27-11ea-86f9-1cc7abbbbc54.PNG)
- Profile activity (in real profile photo is circle, but android studio preview don't show it properly)
![layout_profile](https://user-images.githubusercontent.com/48810274/77111238-44471780-6a27-11ea-939f-939a0be82a3a.PNG)
- Main window activity (blank)
![layout_main](https://user-images.githubusercontent.com/48810274/77111280-5a54d800-6a27-11ea-831e-447de6ce4a96.PNG)

**Comment by MatiDran** [comment]
What a great job Jerzy !
