### ISSUE TITLE
Create training planning functionality (exercises, repetition range, load). Assignet to: Jerzy Kukla

### ISSUE THREAD

**Issue by jacoboDevelops** [EndorFit/EndorFit#2]
how do we iven approach it ? what do we need from users ? i will sketch something in paint how i imagine this and we will go from this. i need it to start doing rest of the stuff  im assigned to

**Comment by JerzyKukla** [comment]
As we talked - I created new activitie (left icon). From this activitie there is a posibilitty to create new plan or exercise.
For now this functionality is only on "Planning feature" branch, but after polishing it a little more I will marge it into master branch.

**Comment by JerzyKukla** [comment]
As you can see "plans" is sub branch of every users own branch.
Branch that will storage informations about done exercises will be implemented similarly way
![image](https://user-images.githubusercontent.com/48810274/80040544-984b8d00-84fa-11ea-9998-ec8dc0dffba1.png)

**Comment by JerzyKukla** [comment]
https://drive.google.com/file/d/1uOjBYIQEo1y6S9wHcFNpZpmucqt2KkW9/view?usp=sharing
