### ISSUE TITLE
Create and implement noSQL database model for storage information about exercises and users activities. Assigned to: Jerzy Kukla

### ISSUE THREAD

**Issue by JerzyKukla** [EndorFit/EndorFit#5]
Below you can see a plan of our NoSQL Database.
If you have some question about it, please ask.

![NoSQL Plan](https://user-images.githubusercontent.com/48810274/80525608-ce24c180-8991-11ea-848e-a8f483d159f6.jpg)

**Comment by jacoboDevelops** [comment]
well thought jerzy !
